//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityNorthwindProject.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategoriler
    {
        public int ID { get; set; }
        public string AD { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public byte IS_FLAG { get; set; }
    }
}
