//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityNorthwindProject.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPARIS_DETAY
    {
        public int ID { get; set; }
        public int SIPARIS_ID { get; set; }
        public int URUN_ID { get; set; }
        public decimal FIYAT { get; set; }
        public int ADET { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public byte IS_FLAG { get; set; }
    }
}
