//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityNorthwindProject.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEDARIKCILER
    {
        public int ID { get; set; }
        public string AD { get; set; }
        public string YETKILI { get; set; }
        public string ADRES { get; set; }
        public string SEHIR { get; set; }
        public string ULKE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<byte> IS_FLAG { get; set; }
    }
}
