//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityNorthwindProject.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_PERSONEL_LIST
    {
        public int ID { get; set; }
        public string TCKN { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string CINSIYET { get; set; }
        public string DOGUM_YERI { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    }
}
