//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityNorthwindProject.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_SIPARIS_DETAY_LIST
    {
        public int SIPARIS_DETAY_ID { get; set; }
        public int URUNLER_ID { get; set; }
        public string URUN_AD { get; set; }
        public decimal FIYAT { get; set; }
        public int ADET { get; set; }
    }
}
