//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityNorthwindProject.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_SIPARIS_LIST
    {
        public int SIPARIS_ID { get; set; }
        public int PERSONEL_ID { get; set; }
        public string PERSONEL_ADYOAD { get; set; }
        public int MUSTERI_ID { get; set; }
        public string MUSTERI_AD { get; set; }
    }
}
